#pragma once

// #include "Node.hpp"
// #include "Node/Expr.hpp"
// #include "Node/Expr/When.hpp"
// #include "Node/Expr/When/Case.hpp"
// #include "Node/Expr/Value.hpp"
// #include "Node/Expr/Function.hpp"
// #include "Node/Expr/Function/Argument.hpp"
// #include "Node/Expr/FunctionCall.hpp"
// #include "Node/Expr/ElementFetch.hpp"
// #include "Node/Expr/VariableFetch.hpp"
// #include "Node/Expr/UnaryOperator.hpp"
// #include "Node/Expr/AssignOperator.hpp"
// #include "Node/Expr/BinaryOperator.hpp"
// #include "Node/Stmt.hpp"
// #include "Node/Stmt/Return.hpp"
// #include "Node/Stmt/Expression.hpp"
// #include "Node/Stmt/VariableDefine.hpp"
// #include "Node/Type.hpp"
// #include "Node/Type/Array.hpp"
// #include "Node/Type/Numeric.hpp"
// #include "Node/Type/Numeric/Float.hpp"
// #include "Node/Type/Numeric/Integer.hpp"
// #include "Node/Type/Function.hpp"
